services:
  - type: web
    name: ms365-mcp
    env: node
    plan: starter           # "free" kan ook, maar slaapt
    region: frankfurt
    buildCommand: |
      npm ci
      npm run build
    startCommand: |
      node dist/index.js --http 10000 --org-mode
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION        # vervangt nodeVersion
        value: 20
      - key: MS365_MCP_CLIENT_ID
        sync: false
      - key: MS365_MCP_CLIENT_SECRET
        sync: false
      - key: MS365_MCP_TENANT_ID
        value: common            # of je tenant-id
      - key: READ_ONLY
        value: "1"
      - key: ENABLED_TOOLS
        value: mail|calendar|files|excel
      - key: LOG_LEVEL
        value: info
